name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nixos:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#nixosConfigurations.nixos.config.system.build.toplevel

  hm-nixos:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#homeConfigurations.sam.activationPackage

  hm-macos:
    runs-on: macos-15
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#homeConfigurations.samueles.activationPackage

  hm-docker-x86:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#homeConfigurations.agent-amd64.activationPackage

  hm-docker-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#homeConfigurations.agent-arm64.activationPackage

  hm-tart:
    runs-on: macos-15
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix build --print-build-logs .#homeConfigurations.admin.activationPackage
