name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nixos:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - run: nix-shell -p nix-info --run "nix-info -m"
      - uses: actions/checkout@v5
      - run: nix build --print-build-logs .#homeConfigurations.sam.activationPackage

  macos:
    runs-on: macos-15
    steps:
      - uses: cachix/install-nix-action@v31
      - run: nix-shell -p nix-info --run "nix-info -m"
      - uses: actions/checkout@v5
      - run: nix build --print-build-logs .#homeConfigurations.samueles.activationPackage
