name: Update
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix flake update 2> >(tee nix-flake-update.txt >&2)
      - uses: actions/upload-artifact@v6
        with:
          name: flake.lock
          path: |
            flake.lock
            nix-flake-update.txt

  nixos:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#nixosConfigurations.nixos.config.system.build.toplevel

  hm-nixos:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#homeConfigurations.sam.activationPackage

  hm-macos:
    needs: lock
    runs-on: macos-15
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#homeConfigurations.samueles.activationPackage

  hm-docker:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#homeConfigurations.agent.activationPackage

  pr:
    needs:
      - lock
      - nixos
      - hm-nixos
      - hm-macos
      - hm-docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - name: Generate pull request body
        id: body
        run: |
          {
            echo 'body<<EOF'
            echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            echo '```'
            cat nix-flake-update.txt
            echo '```'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update `flake.lock`
          branch: update
          title: Update `flake.lock`
          body: ${{ steps.body.outputs.body }}
