name: Update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lock:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix flake update
      - uses: actions/upload-artifact@v6
        with:
          name: flake.lock
          path: flake.lock

  nixos:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#nixosConfigurations.nixos.config.system.build.toplevel

  hm-nixos:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#homeConfigurations.sam.activationPackage

  hm-macos:
    needs: lock
    runs-on: macos-15
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: flake.lock
      - run: nix build --print-build-logs .#homeConfigurations.samueles.activationPackage
